[package]
name = "funcfile"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
open = "5.3.2"
sysinfo = "0.34.2"
image = { version = "0.25", features = ["png"] }
arboard = "3.5.0"
copypasta = "0.10.2"
copypasta-ext = "0.4.4"
