[tasks.build]
description = "Build funcfile"
command = "cargo"
args = ["build", "--release"]

[tasks.dev]
description = "Build funcfile (dev)"
command = "cargo"
args = ["build"]

[tasks.copy_dev]
description = "Copy necessary files"
script_runner = "@duckscript"
script = '''
glob_cp ./hires/* ./target/debug/
'''

[tasks.copy]
description = "Copy necessary files"
script_runner = "@duckscript"
script = '''
glob_cp ./hires/* ./target/release/
'''

[tasks.all]
description = "Build funcfile and copy necessary files"
dependencies = ["build", "copy"]

[tasks.all_dev]
description = "Build funcfile (dev) and copy necessary files"
dependencies = ["dev", "copy_dev"]
